apiVersion: v1
kind: Secret
metadata:
  name: dev-cluster-kube-config
  namespace: p-vcluster-flux-demo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    loft.sh/project-secret-name: vc-connected-host-cluster-{REPLACE_VCLUSTER_NAME}-connected-flux-kubeconfig
type: Opaque


