apiVersion: management.loft.sh/v1
kind: ProjectSecret
metadata:
  name: loft-demos-ghcr-write-pat
  namespace: p-default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    loft.sh/project-secret-name: loft-demos-ghcr-write-pat
    org: loft-demos
    repo: wwt-app
