apiVersion: management.loft.sh/v1
kind: ProjectSecret
metadata:
  name: {REPLACE_ORG_NAME}-ghcr-write-pat
  namespace: p-default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    loft.sh/project-secret-name: {REPLACE_ORG_NAME}-ghcr-write-pat
    org: {REPLACE_ORG_NAME}
    repo: {REPLACE_REPO_NAME}
